steps:
- id: 'Unit Tests'
  name: 'europe-west2-docker.pkg.dev/ons-sdx-ci/sdx-apps/sdx-gcp:1.4.5'
  script: |
    #!/usr/bin/env bash
    poetry export -f requirements.txt --output requirements.txt
    pip install -r requirements.txt
    flake8 . --count --statistics
    pytest -v --cov-report term-missing --disable-warnings --cov=app tests/
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
