title: "Build Spec for Prodcom"
survey_id: "???" #TODO
target: "SDS"
period_format: "YYYYM"
item_list_path: "items.products"
template:
    schema_version: "v1"
    identifier: "#ruref"
    note:
        title: "$NOTE_TITLE"
        description: "$NOTE_DESC"
    items:
        products:
            -   identifier: "#luref"
                name: "$name"
                cn_codes: "#cncode?"
                guidance_include:
                    title: "#guidance_include_title"
                    list: ["example1", "example2"]
                guidance_exclude:
                    title: "#guidance_exclude_title"
                    list: ["example1", "example2"]
                value_sales:
                    answer_code: "#value_sales_answer_code"
                    label: "#value_sales_label"
                volume_sales:
                    answer_code: "#volume_sales_answer_code"
                    label: "#volume_sales_label"
                total_volume:
                    answer_code: "#total_volume_answer_code"
                    label: "#total_volume_label"
                    unit_label: "#total_volume_unit_label"
transforms:
    "NOTE_TITLE":
        name: "CONCAT"
        args:
            value: "#luname1"
            values: ["#luname2", "#luname3"]
            seperator: " "
