title: "Build Spec for Prodcom"
survey_id: "???" #TODO
target: "SDS"
period_format: "YYYYM"
item_list_path: "items.products"
template:
    schema_version: "v1"
    identifier: "#ruref"
    note:
        title: "$NOTE_TITLE"
        description: "$NOTE_DESC"
    items:
        products:
            -   identifier: "#luref"
                name: "???"
                cn_codes: "???"
                guidance_include: "???"
                guidance_exclude: "???"
                value_sales: "???"
                volume_sales: "???"
                total_volume: "???"
transforms:
    "NOTE_TITLE":
        name: "CONCAT"
        args:
            value: "#luname1"
            values: ["#luname2", "#luname3"]
            seperator: " "
