name: Check Pyproject Version

on:
  pull_request:
    branches:
      - '*'

jobs:
  uv-example:
    permissions:
      contents: read
    name: Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies using UV
        run: |
          uv sync

      - name: Check version in pyproject.toml
        run: |
          uv run python scripts/check_version.py
